In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
df=pd.read_csv('/content/heart.csv',encoding='latin1')
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [ ]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
dfle = df
dfle.ChestPainType = le.fit_transform(dfle.ChestPainType)
dfle.RestingECG = le.fit_transform(dfle.RestingECG)
dfle.ExerciseAngina = le.fit_transform(dfle.ExerciseAngina)
dfle.Sex = le.fit_transform(dfle.Sex)
dfle.ST_Slope = le.fit_transform(dfle.ST_Slope)
dfle
X = dfle[['Age','ChestPainType','RestingBP','Cholesterol','RestingECG','MaxHR','ExerciseAngina',"Sex", "FastingBS","ST_Slope","Oldpeak"]]
y = dfle['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
X_train

,Age,ChestPainType,RestingBP,Cholesterol,RestingECG,MaxHR,ExerciseAngina,Sex,FastingBS,ST_Slope,Oldpeak
429,63,2,133,0,0,120,1,1,0,1,1.0
51,47,0,120,205,1,98,1,0,0,1,2.0
74,55,0,140,268,1,128,1,1,0,1,1.5
365,64,0,200,0,1,140,1,0,0,1,1.0
686,57,0,120,354,1,163,1,0,0,2,0.6
...,...,...,...,...,...,...,...,...,...,...,...
748,64,0,120,246,0,96,1,1,0,0,2.2
367,68,0,135,0,2,120,1,1,0,2,0.0
655,40,0,152,223,1,181,0,1,0,2,0.0
716,67,0,120,237,1,71,0,1,0,1,1.0
208,28,1,130,132,0,185,0,1,0,2,0.0

In [ ]:
X_test

,Age,ChestPainType,RestingBP,Cholesterol,RestingECG,MaxHR,ExerciseAngina,Sex,FastingBS,ST_Slope,Oldpeak
628,61,3,134,234,1,145,0,1,0,1,2.6
11,58,1,136,164,2,99,1,1,0,1,2.0
765,41,2,112,250,1,179,0,1,0,2,0.0
307,53,1,130,0,2,120,0,1,0,0,0.7
183,46,0,110,238,2,140,1,1,0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...
902,58,1,125,220,1,144,0,1,0,1,0.4
535,56,0,130,0,0,122,1,1,0,1,1.0
47,50,1,140,216,1,170,0,1,0,2,0.0
648,59,0,170,326,0,140,1,1,0,0,3.4
209,54,0,125,216,1,140,0,1,0,1,0.0

In [ ]:
y_train

429    1
51     1
74     1
365    1
686    0
      ..
748    1
367    1
655    1
716    1
208    0
Name: HeartDisease, Length: 734, dtype: int64

In [ ]:
y_test

628    1
11     1
765    0
307    0
183    0
      ..
902    0
535    1
47     0
648    1
209    1
Name: HeartDisease, Length: 184, dtype: int64

In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_predicted = clf.predict(X_test)

In [ ]:
clf.predict_proba(X_test)

array([[0.59246412, 0.40753588],
       [0.10478707, 0.89521293],
       [0.95082326, 0.04917674],
       [0.07469494, 0.92530506],
       [0.16012409, 0.83987591],
       [0.24508464, 0.75491536],
       [0.04509228, 0.95490772],
       [0.84647818, 0.15352182],
       [0.74845226, 0.25154774],
       [0.68642616, 0.31357384],
       [0.81730508, 0.18269492],
       [0.93455273, 0.06544727],
       [0.04625185, 0.95374815],
       [0.95970367, 0.04029633],
       [0.04474853, 0.95525147],
       [0.00217781, 0.99782219],
       [0.04309182, 0.95690818],
       [0.95759464, 0.04240536],
       [0.8088576 , 0.1911424 ],
       [0.09865332, 0.90134668],
       [0.97225338, 0.02774662],
       [0.17902545, 0.82097455],
       [0.00948133, 0.99051867],
       [0.65882262, 0.34117738],
       [0.99179172, 0.00820828],
       [0.17180443, 0.82819557],
       [0.85875704, 0.14124296],
       [0.25073399, 0.74926601],
       [0.97317759, 0.02682241],
       [0.01596248, 0.98403752],
       [0.21934917, 0.78065083],
       [0.26015535, 0.73984465],
       [0.89524768, 0.10475232],
       [0.25749903, 0.74250097],
       [0.8122153 , 0.1877847 ],
       [0.10349416, 0.89650584],
       [0.2127316 , 0.7872684 ],
       [0.70529818, 0.29470182],
       [0.0874758 , 0.9125242 ],
       [0.51413236, 0.48586764],
       [0.89971062, 0.10028938],
       [0.23312288, 0.76687712],
       [0.04428009, 0.95571991],
       [0.88525896, 0.11474104],
       [0.36126361, 0.63873639],
       [0.18583605, 0.81416395],
       [0.68934859, 0.31065141],
       [0.04695001, 0.95304999],
       [0.7438222 , 0.2561778 ],
       [0.70717169, 0.29282831],
       [0.04490296, 0.95509704],
       [0.07945215, 0.92054785],
       [0.84283186, 0.15716814],
       [0.59789584, 0.40210416],
       [0.80991174, 0.19008826],
       [0.03258813, 0.96741187],
       [0.09225296, 0.90774704],
       [0.32586064, 0.67413936],
       [0.85395332, 0.14604668],
       [0.43720385, 0.56279615],
       [0.35369696, 0.64630304],
       [0.52303313, 0.47696687],
       [0.16253099, 0.83746901],
       [0.4458319 , 0.5541681 ],
       [0.09868038, 0.90131962],
       [0.31636091, 0.68363909],
       [0.01232118, 0.98767882],
       [0.96715535, 0.03284465],
       [0.74115493, 0.25884507],
       [0.24480019, 0.75519981],
       [0.8805756 , 0.1194244 ],
       [0.00262974, 0.99737026],
       [0.66563048, 0.33436952],
       [0.8240424 , 0.1759576 ],
       [0.78702814, 0.21297186],
       [0.92915488, 0.07084512],
       [0.58216538, 0.41783462],
       [0.09071004, 0.90928996],
       [0.03767155, 0.96232845],
       [0.50925306, 0.49074694],
       [0.12447885, 0.87552115],
       [0.10123475, 0.89876525],
       [0.66002845, 0.33997155],
       [0.94632594, 0.05367406],
       [0.90216167, 0.09783833],
       [0.09912685, 0.90087315],
       [0.91588769, 0.08411231],
       [0.12755927, 0.87244073],
       [0.01496432, 0.98503568],
       [0.79332411, 0.20667589],
       [0.90913889, 0.09086111],
       [0.93317861, 0.06682139],
       [0.02274868, 0.97725132],
       [0.87071735, 0.12928265],
       [0.04448067, 0.95551933],
       [0.02613939, 0.97386061],
       [0.8248613 , 0.1751387 ],
       [0.89579644, 0.10420356],
       [0.10737061, 0.89262939],
       [0.91654017, 0.08345983],
       [0.92839862, 0.07160138],
       [0.37661565, 0.62338435],
       [0.0335489 , 0.9664511 ],
       [0.51389903, 0.48610097],
       [0.8630401 , 0.1369599 ],
       [0.90577438, 0.09422562],
       [0.89820018, 0.10179982],
       [0.96290244, 0.03709756],
       [0.05007389, 0.94992611],
       [0.76797556, 0.23202444],
       [0.0284471 , 0.9715529 ],
       [0.02148792, 0.97851208],
       [0.87282291, 0.12717709],
       [0.12942848, 0.87057152],
       [0.05120211, 0.94879789],
       [0.17864883, 0.82135117],
       [0.10385803, 0.89614197],
       [0.17540686, 0.82459314],
       [0.06761242, 0.93238758],
       [0.79613301, 0.20386699],
       [0.91782222, 0.08217778],
       [0.86653282, 0.13346718],
       [0.01767436, 0.98232564],
       [0.3136351 , 0.6863649 ],
       [0.00630998, 0.99369002],
       [0.11258056, 0.88741944],
       [0.8991508 , 0.1008492 ],
       [0.51685129, 0.48314871],
       [0.14766455, 0.85233545],
       [0.96968852, 0.03031148],
       [0.00214132, 0.99785868],
       [0.21050383, 0.78949617],
       [0.03804654, 0.96195346],
       [0.14671879, 0.85328121],
       [0.65891434, 0.34108566],
       [0.82142834, 0.17857166],
       [0.95065181, 0.04934819],
       [0.94910854, 0.05089146],
       [0.9764149 , 0.0235851 ],
       [0.3102154 , 0.6897846 ],
       [0.05071852, 0.94928148],
       [0.06832067, 0.93167933],
       [0.89680507, 0.10319493],
       [0.95751674, 0.04248326],
       [0.78672625, 0.21327375],
       [0.28490996, 0.71509004],
       [0.33619947, 0.66380053],
       [0.89922343, 0.10077657],
       [0.15418251, 0.84581749],
       [0.93009664, 0.06990336],
       [0.82126841, 0.17873159],
       [0.9582447 , 0.0417553 ],
       [0.45901749, 0.54098251],
       [0.15570382, 0.84429618],
       [0.0466354 , 0.9533646 ],
       [0.3045399 , 0.6954601 ],
       [0.86115444, 0.13884556],
       [0.9240708 , 0.0759292 ],
       [0.17538881, 0.82461119],
       [0.70182923, 0.29817077],
       [0.45642385, 0.54357615],
       [0.29453441, 0.70546559],
       [0.20577512, 0.79422488],
       [0.33282185, 0.66717815],
       [0.89216284, 0.10783716],
       [0.74546809, 0.25453191],
       [0.91044792, 0.08955208],
       [0.8744798 , 0.1255202 ],
       [0.81243422, 0.18756578],
       [0.42081581, 0.57918419],
       [0.89534627, 0.10465373],
       [0.96902049, 0.03097951],
       [0.38852264, 0.61147736],
       [0.13197749, 0.86802251],
       [0.81426161, 0.18573839],
       [0.13963785, 0.86036215],
       [0.89288425, 0.10711575],
       [0.00975078, 0.99024922],
       [0.92095395, 0.07904605],
       [0.45237553, 0.54762447],
       [0.03992205, 0.96007795],
       [0.84380895, 0.15619105],
       [0.00890928, 0.99109072],
       [0.33601273, 0.66398727]])

In [ ]:
y_predicted

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1])

In [ ]:
clf.score(X_test, y_test)

0.8695652173913043